name: publish to nuget
on:
  push:
    branches: [nuget]

env:
  config: "Release"

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.200"
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}
          nuget-version: "5.3.1"
      - name: Build sdk
        run: dotnet build /src/CodeMash.Sdk.sln --configuration $config
      - name: Nuget restore
        run: nuget restore $GITHUB_WORKSPACE/src/CodeMash.Sdk.sln
      - name: Pack nuget package
        run: $GITHUB_WORKSPACE/build.sh
